import streamlit as st
import base64
from PIL import Image

# Adding background image to Home page
def add_bg_from_local(image_file):
    with open(image_file, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read())
    st.markdown(
        f"""
    <style>
    .stApp {{
        background-image: url(data:image/{"png"};base64,{encoded_string.decode()});
        background-size: cover
    }}
    </style>
    """,
        unsafe_allow_html=True,
    )

# Load background images
add_bg_from_local("storage/frontend/logo.jpeg")
image_id = Image.open("/home/storage/frontend/id.png")
image_stablediff = Image.open("/home/storage/frontend/butterfly.jpeg")
# Page title
st.write("# ESCERCLOUD AI Computer Vision Services - Demo! 👋")
# Page description
st.write("# Document Understanding")
st.write(
    "###### Document understanding is the process of automatically extracting, classifying, interpreting, contextualising, and searching information from documents using machine learning, computer vision, and natural language processing technologies. Major use cases include KYC, KYB, reviewing text within legal contracts, leases, and other documents to automate business processes."
)
st.image(image_id)
st.markdown(
    """ # Stable Diffusion 
###### Stable Diffusion includes text-to-image,and image-to-image models that enables users to create stunning art within seconds. **Versions1**  and **Version 2** of Stable Diffusion generate images with resolutions of **512x512** and **768x768** pixels in turn, respectively, in a matter of seconds."""
)
st.image(
    image_stablediff,
    caption=" image generated by stable  diffudion with the prompt of beautiful butterfly anatomy diagram, bold shūji, chart, schematics, infographic, scientific, measurements, abstract, surreal, collage, new media design, poster, colorful highlights, tarot card, glowing ruins, marginalia, 8k, extremely detailed, dark color palette + style of Katsuhiro Otomo + Masamune Shirow + pantone, on black canvas, typography annotations",
)

st.sidebar.success("Select a demo above.")
