apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-server.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend-stable-v1-1
  name: backend_stable_v1_1
spec:
  ports:
    - name: "8504"
      port: 8504
      targetPort: 8504
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: backend-stable-v1-1
status:
  loadBalancer: {}
