apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-server.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
